### ISSUE TITLE
NullPointerException for buyer NPC

### ISSUE THREAD

**Issue by Xericore** [Dandielo/dtlTraders#49]
Using latest dtlTraders-3.3-SNAPSHOT.jar (Build 25) as well as spigot-1.8.3 and latest citizens-2.0.15 (Build 1219).
Hi, NPC that sell items work fine, but if they buy something, this exception occurs when right clicking the NPC. I hope the following helps you resolve the issue:
# Stacktrace
```
[18:27:21] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to dtlTraders v3.2.0-snapshot
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:278) [citizens-2.0.15-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:1287) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:52) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:11) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_60]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_60]
Caused by: java.lang.NullPointerException
	at net.dandielo.citizens.traders_v3.traders.transaction.participants.TraderParticipant.check(TraderParticipant.java:31) ~[?:?]
	at net.dandielo.citizens.traders_v3.utils.items.attributes.Price.allowTransaction(Price.java:108) ~[?:?]
	at net.dandielo.citizens.traders_v3.utils.items.attributes.Price.getDescription(Price.java:113) ~[?:?]
	at net.dandielo.citizens.traders_v3.traders.transaction.ShopSession.getDescription(ShopSession.java:87) ~[?:?]
	at net.dandielo.citizens.traders_v3.traders.stock.StockPlayer.setInventory(StockPlayer.java:47) ~[?:?]
	at net.dandielo.citizens.traders_v3.traders.stock.StockPlayer.getInventory(StockPlayer.java:28) ~[?:?]
	at net.dandielo.citizens.traders_v3.traders.types.Server.onRightClick(Server.java:112) ~[?:?]
	at net.dandielo.citizens.traders_v3.tNpcListener.npcRightClickEvent(tNpcListener.java:345) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
	... 24 more
```

# The NPC from saves.yml
```
  '31':
    name: "\xa7cXephos"
    uuid: 77b6ede4-0dc0-45e8-96b0-96c52138201e
    traits:
      wallet:
        player-uuid: none
        type: infinite
        money: 0.0
      inventory: {}
      trader:
        type: server
        owner-uuid: none
        patterns: []
        sell: []
        buy:
        - diamond s:0 p:100.00 a:1
        - gold_ingot s:2 p:50.00 a:1
        - iron_ingot s:4 p:10.00 a:1
        stock:
          default: buy
      location:
        world: Kratanien
        x: '5.423657067284029'
        y: '80.0625'
        z: '-8.42914375154863'
        yaw: '-1.6860504150390625'
        pitch: '2.069162607192993'
      spawned: true
      equipment:
        helmet:
          type: LEATHER_HELMET
          amount: 1
          durability: 0
          mdata: 0
          meta:
            armor:
              color: 10040115
        leggings:
          type: LEATHER_LEGGINGS
          amount: 1
          durability: 0
          mdata: 0
          meta:
            armor:
              color: 10040115
        boots:
          type: LEATHER_BOOTS
          amount: 1
          durability: 0
          mdata: 0
          meta:
            armor:
              color: 10040115
      text:
        talk-close: true
        random-talker: true
        realistic-looking: false
        range: '5.0'
        talkitem: default
        text:
          '0': I will give you money for your goods!
      speech: chat
      owner:
        owner: server
        uuid: ''
      lookclose:
        enabled: true
        range: '5.0'
        realisticlooking: false
    traitnames: inventory,text,trader,spawned,speech,type,equipment,owner,wallet,location,lookclose
    navigator:
      pathfindingrange: '25.0'
      stationaryticks: -1
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true
    metadata:
      cached-skin-uuid: 2c6d7b3d-7674-4b18-8d86-bb6a707ea8e4
      cached-skin-uuid-name: Xephos
```
# Some debug after meddling with the sell stock of a new NPC:
```
[18:43:27] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] While executing inventory click event
[18:43:27] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Exception: InvocationTargetException
[18:43:27] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Method: generalUI
[18:43:27] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Trader: Adf, player: Xericore
[18:43:27] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Exception message: null
[18:43:27] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] While executing inventory click event
[18:43:27] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Exception: InvocationTargetException
[18:43:27] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Method: __topUpdate
[18:43:27] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Trader: Adf, player: Xericore
[18:43:27] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Exception message: null
```

**Comment by Dandielo** [comment]
Ok, looking at this I'm almost sure how to fix it

Will try to do it today :)

**Comment by Xericore** [comment]
Well that was a quick response. Thank you for your effort with this plugin.

**Comment by Dandielo** [comment]
Just pushed a fix for it, you may look on the CI server and try it out :)

**Comment by Xericore** [comment]
Hi, unfortunately that didn't fix it yet.
Now I'm getting this error just after right clicking the npc:
```
[23:44:24] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to dtlTraders v3.2.0-snapshot
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:278) [citizens-2.0.15-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:1287) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:52) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:11) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_60]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_60]
Caused by: java.lang.NullPointerException
	at net.dandielo.citizens.traders_v3.traders.transaction.participants.TraderParticipant.check(TraderParticipant.java:31) ~[?:?]
	at net.dandielo.citizens.traders_v3.utils.items.attributes.Price.allowTransaction(Price.java:108) ~[?:?]
	at net.dandielo.citizens.traders_v3.utils.items.attributes.Price.getDescription(Price.java:113) ~[?:?]
	at net.dandielo.citizens.traders_v3.traders.transaction.ShopSession.getDescription(ShopSession.java:88) ~[?:?]
	at net.dandielo.citizens.traders_v3.traders.stock.StockPlayer.setInventory(StockPlayer.java:47) ~[?:?]
	at net.dandielo.citizens.traders_v3.traders.stock.StockPlayer.getInventory(StockPlayer.java:28) ~[?:?]
	at net.dandielo.citizens.traders_v3.traders.types.Server.onRightClick(Server.java:112) ~[?:?]
	at net.dandielo.citizens.traders_v3.TEntityListener.npcRightClickEvent(TEntityListener.java:345) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.3.jar:git-Spigot-529ff99-7f52bd6]
	... 24 more
```

After that, I opened the inventory and in creative mode tried to drag an item to the bottom slots. This was the result:
```
[23:45:54] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] While executing inventory click event
[23:45:54] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Exception: InvocationTargetException
[23:45:54] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Method: __bottomUpdate
[23:45:54] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Trader: Xephos, player: Xericore
[23:45:54] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Exception message: null
```

In survival: Trying to move an item from in inventory (which fails):
```
[23:48:32] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Exception: InvocationTargetException
[23:48:32] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Method: __topUpdate
[23:48:32] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Trader: Xephos, player: Xericore
[23:48:32] [Server thread/INFO]: [dtlTraders][DEBUG][CRITICAL] Exception message: null

```
